/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.person;

import javax.swing.JPanel;
import model.personDirectory;


/**
 *
 * @author hardiksodhani
 */
public class ManagePersons extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonPanel
     */
    private personDirectory personDirectory;
    private JPanel userProcessContainer;
    public ManagePersons( JPanel  userProcessContainer, personDirectory personDirectory) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mpJPanel = new javax.swing.JPanel();
        btnRefresh1 = new javax.swing.JButton();
        txtSearchPerson1 = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPersonDirectory1 = new javax.swing.JTable();
        btnBack1 = new javax.swing.JButton();
        btnCreatePerson1 = new javax.swing.JButton();
        btnView1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnSearch1 = new javax.swing.JButton();

        btnRefresh1.setText("Refresh");

        label3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        label3.setText("Person Directory");

        tblPersonDirectory1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Person Name", "Age", "Patient ID"
            }
        ));
        jScrollPane2.setViewportView(tblPersonDirectory1);

        btnBack1.setText("<<Back");

        btnCreatePerson1.setText("Create Person");

        btnView1.setText("View Person");

        btnEdit1.setText("Edit Person");

        btnDelete1.setText("Delete Person");

        btnSearch1.setText("Search Person");

        javax.swing.GroupLayout mpJPanelLayout = new javax.swing.GroupLayout(mpJPanel);
        mpJPanel.setLayout(mpJPanelLayout);
        mpJPanelLayout.setHorizontalGroup(
            mpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mpJPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mpJPanelLayout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mpJPanelLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(btnSearch1)
                    .addGap(50, 50, 50)
                    .addComponent(txtSearchPerson1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                    .addComponent(btnRefresh1)
                    .addGap(157, 157, 157))
                .addGroup(mpJPanelLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(btnBack1)
                    .addGap(30, 30, 30)
                    .addComponent(btnCreatePerson1)
                    .addGap(30, 30, 30)
                    .addComponent(btnView1)
                    .addGap(30, 30, 30)
                    .addComponent(btnEdit1)
                    .addGap(30, 30, 30)
                    .addComponent(btnDelete1)
                    .addGap(345, 345, 345)))
        );
        mpJPanelLayout.setVerticalGroup(
            mpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mpJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(mpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mpJPanelLayout.createSequentialGroup()
                    .addGap(281, 281, 281)
                    .addGroup(mpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack1)
                        .addComponent(btnCreatePerson1)
                        .addComponent(btnView1)
                        .addComponent(btnEdit1)
                        .addComponent(btnDelete1))
                    .addGap(35, 35, 35)
                    .addGroup(mpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch1)
                        .addComponent(btnRefresh1)
                        .addComponent(txtSearchPerson1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mpJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mpJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCreatePerson1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnView1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label3;
    private javax.swing.JPanel mpJPanel;
    private javax.swing.JTable tblPersonDirectory1;
    private javax.swing.JTextField txtSearchPerson1;
    // End of variables declaration//GEN-END:variables
}
